services:
  martin_portefolie:
    build:
      context: .
      args: { APP_ENV: prod }
    image: martin_portefolie:prod
    environment:
      APP_ENV: prod
      SERVER_NAME: ":80"                           # Caddy listens HTTP only; Traefik terminates TLS
      CADDY_GLOBAL_OPTIONS: "auto_https off"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      MESSENGER_TRANSPORT_DSN: "sync://"
      MAILER_DSN: "null://null"
      APP_DEBUG: "0"
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.martin.loadbalancer.server.port=80"

      # ── HTTP (80) → redirect to HTTPS for both apex and www
      - "traefik.http.middlewares.force-https.redirectscheme.scheme=https"
      - "traefik.http.routers.martin-web.rule=Host(`martindeveloper.dk`) || Host(`www.martindeveloper.dk`)"
      - "traefik.http.routers.martin-web.entrypoints=web"
      - "traefik.http.routers.martin-web.middlewares=force-https"
      - "traefik.http.routers.martin-web.service=noop@internal"

      # ── HTTPS (443) content router for apex (canonical)
      - "traefik.http.routers.martin.rule=Host(`martindeveloper.dk`)"
      - "traefik.http.routers.martin.entrypoints=websecure"
      - "traefik.http.routers.martin.tls.certresolver=le"

      # ── HTTPS (443) www → apex redirect
      - "traefik.http.middlewares.www2apex-martin.redirectregex.regex=^https?://www\\.martindeveloper\\.dk/(.*)"
      - "traefik.http.middlewares.www2apex-martin.redirectregex.replacement=https://martindeveloper.dk/$1"
      - "traefik.http.middlewares.www2apex-martin.redirectregex.permanent=true"
      - "traefik.http.routers.martin-www.rule=Host(`www.martindeveloper.dk`)"
      - "traefik.http.routers.martin-www.entrypoints=websecure"
      - "traefik.http.routers.martin-www.tls.certresolver=le"
      - "traefik.http.routers.martin-www.middlewares=www2apex-martin"
      - "traefik.http.routers.martin-www.service=noop@internal"

    restart: unless-stopped

networks:
  web:
    external: true
