services:
  martin_portefolie:
    build: .
    container_name: martin_portefolie
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    working_dir: /app
    restart: unless-stopped
    networks:
      - martin-network

volumes:
  caddy_data:

networks:
  martin-network:
    external: false
