services:
  nginx:
    image: nginx:latest
    container_name: portefolio_nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"

      # Primary router for non-www
      - "traefik.http.routers.portefolio.rule=Host(`martindeveloper.online`)"
      - "traefik.http.routers.portefolio.entrypoints=web,websecure"
      - "traefik.http.routers.portefolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portefolio.loadbalancer.server.port=80"

      # Additional router for www
      - "traefik.http.routers.portefolio-www.rule=Host(`www.martindeveloper.online`)"
      - "traefik.http.routers.portefolio-www.entrypoints=web,websecure"
      - "traefik.http.routers.portefolio-www.tls.certresolver=letsencrypt"
      - "traefik.http.services.portefolio-www.loadbalancer.server.port=80"

      # Force redirect to HTTPS
      - "traefik.http.routers.portefolio.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"


  php:
    build: .
    image: php:8.3-fpm
    container_name: portefolio_php-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - dokploy-network

  database:
    image: mariadb:10.11.2
    container_name: portefolio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3308:3306"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
