services:
  martin_portefolie:
    build: .
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      APP_ENV: ${APP_ENV:-dev} # Use dev by default
    tty: true

volumes:
  caddy_data:
  caddy_config:
