services:
  martin_portefolie:
    build:
      context: .
      args: { APP_ENV: prod }
    image: martin_portefolie:prod
    environment:
      APP_ENV: prod
      SERVER_NAME: ":80"
      CADDY_GLOBAL_OPTIONS: "auto_https off"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      MESSENGER_TRANSPORT_DSN: "sync://"
      MAILER_DSN: "null://null"
      APP_DEBUG: "1"
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.martin.loadbalancer.server.port=80"

      - "traefik.http.routers.martin.rule=Host(`martindeveloper.dk`) || Host(`www.martindeveloper.dk`)"
      - "traefik.http.routers.martin.entrypoints=websecure"
      - "traefik.http.routers.martin.tls.certresolver=le"

      - "traefik.http.middlewares.martin-https.redirectscheme.scheme=https"
      - "traefik.http.routers.martin-web.rule=Host(`martindeveloper.dk`) || Host(`www.martindeveloper.dk`)"
      - "traefik.http.routers.martin-web.entrypoints=web"
      - "traefik.http.routers.martin-web.middlewares=martin-https@docker"
      - "traefik.http.routers.martin-web.service=martin"
    restart: unless-stopped

networks:
  web:
    external: true
