services:
  app:
    build:
      context: .
      args: { APP_ENV: dev }
    container_name: martin_dev
    ports: ["8080:80"]
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"                 # accept any host
      CADDY_GLOBAL_OPTIONS: "auto_https off"
    volumes:
      - ./:/app
      - dev_vendor:/app/vendor
      - dev_var:/app/var
    tty: true
volumes:
  dev_vendor:
  dev_var:
