services:
  app:
    image: dunglas/frankenphp
    container_name: projecta_frankenphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - caddy_data:/data  # Caddy's cert-data
    restart: unless-stopped

volumes:
  caddy_data: