services:
  martin_portefolie:
    build:
      context: .
      args: { APP_ENV: prod }
    image: martin_portefolie:prod
    environment:
      APP_ENV: prod
      SERVER_NAME: ${SERVER_NAME:-martindeveloper.dk}
      CADDY_GLOBAL_OPTIONS: ""   # keep empty in prod
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.martin.rule=Host(`${SERVER_NAME:-martindeveloper.dk}`)
      - traefik.http.routers.martin.entrypoints=websecure
      - traefik.http.routers.martin.tls.certresolver=le
      - traefik.http.services.martin.loadbalancer.server.port=80
      # HTTP -> HTTPS redirect (no file provider needed)
      - traefik.http.middlewares.martin-https.redirectscheme.scheme=https
      - traefik.http.routers.martin-web.rule=Host(`${SERVER_NAME:-martindeveloper.dk}`)
      - traefik.http.routers.martin-web.entrypoints=web
      - traefik.http.routers.martin-web.middlewares=martin-https
    restart: unless-stopped
networks:
  web:
    external: true
